using Ncx.Acceptance.Examples;

namespace Ncx.Acceptance.Cli;

/// <summary>
/// ncx trace &lt;file&gt; [--format text|csv] and the shared options: one row per changed state variable per executed
/// block, channel, block, variable, old, new, old empty when unknown (virtual machine 6; architecture 10; P1-07).
/// </summary>
public sealed class TraceCommandTests : IDisposable
{
    private readonly CliHarness _cli = new();

    public void Dispose()
    {
        _cli.Dispose();
    }

    // P1-07: trace runs on every example, exit 0 without a machine file (D97, D103), and writes its table.
    [Theory]
    [MemberData(nameof(ExampleCheckTests.Examples), MemberType = typeof(ExampleCheckTests))]
    public void Trace_Example_ExitsZeroAndWritesTheTable(string example)
    {
        string file = _cli.CopyExample(example);

        int exitCode = _cli.Run("trace", file);

        Assert.True(exitCode == 0, _cli.Error);
        Assert.StartsWith("channel  block  variable", _cli.Output, StringComparison.Ordinal);
    }

    // P1-07, phases table row 1: the trace of 2.5D_FRAESEN as an expected file, in aligned text.
    [Fact]
    public void Trace_Fraesen25D_EqualsTheExpectedFile()
    {
        string file = _cli.CopyExample("2.5D_FRAESEN.ncx");

        _cli.Run("trace", file);

        CliHarness.AssertExpectedFile("2.5D_FRAESEN.trace.txt", _cli.Output);
    }

    // VM 6: the columns channel, block, variable, old, new; old empty when unknown (X and Y before the first RAPID).
    [Fact]
    public void TraceCsv_Fraesen25D_WritesTheColumnsAndAnEmptyOldValueWhenUnknown()
    {
        string file = _cli.CopyExample("2.5D_FRAESEN.ncx");

        int exitCode = _cli.Run("trace", file, "--format", "csv");

        Assert.Equal(0, exitCode);
        string[] lines = _cli.Output.Split('\n');
        Assert.Equal("channel,block,variable,old,new", lines[0]);
        Assert.Equal("1,5,UNITS,,MM", lines[1]);
        Assert.Contains("1,15,X,,50.4", lines);
        Assert.Contains("1,15,Y,,-7.025", lines);
        Assert.Contains("1,21,X,50.4,7", lines);
    }

    // VM 6, 2.7: the variables are state variables of the channel; VAR sets them, named by the key that sets them
    // (virtual machine 3.10), and an expression STATIC mode does not evaluate leaves the new value empty (VM 1).
    [Fact]
    public void TraceCsv_PatternLoop_WritesTheVariables()
    {
        string file = _cli.CopyExample("PATTERN_LOOP.ncx");

        _cli.Run("trace", file, "--format", "csv");

        string[] lines = _cli.Output.Split('\n');
        Assert.Contains("1,8,VAR:Q1,,10", lines);
        Assert.Contains("1,9,VAR:Q2,,5", lines);
        Assert.Contains("1,18,VAR:Q1,10,", lines);
        Assert.Contains("1,19,VAR:Q3,0,", lines);
    }

    // VM 6, D99: a block of a subprogram that STATIC mode walks at several calls appears once per walk; CALL=100
    // TIMES=4 walks line 33 four times, each from the state the pass before left.
    [Fact]
    public void TraceCsv_SubprogramCalledFourTimes_AppearsOncePerWalk()
    {
        string file = _cli.CopyExample("INCREMENTAL_SUB.ncx");

        _cli.Run("trace", file, "--format", "csv");

        var rowsOfLine33 = new List<string>();
        foreach (string line in _cli.Output.Split('\n'))
        {
            if (line.StartsWith("1,33,Y,", StringComparison.Ordinal))
            {
                rowsOfLine33.Add(line);
            }
        }

        Assert.Equal(["1,33,Y,0,15", "1,33,Y,15,30", "1,33,Y,30,45", "1,33,Y,45,60"], rowsOfLine33);
    }

    // A value with a comma or a quote is written as a CSV field in quotes, its quotes doubled.
    [Fact]
    public void TraceCsv_StringWithACommaAndQuotes_IsQuoted()
    {
        string file = _cli.WriteFile("string.ncx", CliHarness.OneProgram("VAR:QS1=\"a,b\""));

        int exitCode = _cli.Run("trace", file, "--format", "csv");

        Assert.True(exitCode == 0, _cli.Error);
        Assert.Contains("1,3,VAR:QS1,,\"\"\"a,b\"\"\"", _cli.Output.Split('\n'));
    }

    // VM 3.10: generated blocks appear in trace with their origin, the rule that made them and why; the rows of the
    // coolant clutch rule of machine-config 5a stand around the coolant block they were generated for.
    [Fact]
    public void TraceCsv_GeneratedBlocks_NameTheirOrigin()
    {
        string file = _cli.WriteFile("clutch.ncx",
            CliHarness.OneProgram("UNITS=MM", "SPINDLE=CW RPM=1500", "COOLANT:THROUGH=ON"));
        string machine = _cli.WriteFile("clutch.toml", TestMachines.ClutchMill);

        int exitCode = _cli.Run("trace", file, "--format", "csv", "--machine", machine);

        Assert.True(exitCode == 0, _cli.Error);
        string[] lines = _cli.Output.Split('\n');
        int stop = Array.IndexOf(lines, "1,5 generated by [coolant] THROUGH (requires),SPINDLE:S1,CW,OFF");
        int coolant = Array.IndexOf(lines, "1,5,COOLANT:THROUGH,OFF,ON");
        int restart = Array.IndexOf(lines, "1,5 generated by [coolant] THROUGH (restore),SPINDLE:S1,OFF,CW");
        Assert.True(stop > 0 && stop < coolant && coolant < restart, _cli.Output);
    }

    // The text format aligns the columns, two spaces apart (VM 8: CSV or aligned columns).
    [Fact]
    public void TraceText_Rows_AreAlignedInColumns()
    {
        string file = _cli.WriteFile("aligned.ncx", CliHarness.OneProgram("UNITS=MM", "FEED_MODE=PER_REV"));

        _cli.Run("trace", file, "--format", "text");

        Assert.Equal(
            CliHarness.Lines(
                "channel  block  variable   old      new",
                "1        3      UNITS               MM",
                "1        4      FEED_MODE  PER_MIN  PER_REV",
                "1        5      FEED_MODE  PER_REV  PER_MIN"),
            _cli.Output);
    }

    // An ERROR of the parser means no run: no table, exit 1 (D97).
    [Fact]
    public void Trace_UnknownKey_WritesNothingAndExitsOne()
    {
        string file = _cli.WriteFile("unknown.ncx", CliHarness.OneProgram("LINE X=1 SPEED=5"));

        int exitCode = _cli.Run("trace", file);

        Assert.Equal(1, exitCode);
        Assert.Equal("", _cli.Output);
        Assert.Contains("ERROR PAR010", _cli.Error, StringComparison.Ordinal);
    }

    // --format takes text or csv; anything else is a usage error, exit 2 (D97).
    [Fact]
    public void TraceFormat_Unknown_IsAUsageError()
    {
        string file = _cli.CopyExample("2.5D_FRAESEN.ncx");

        int exitCode = _cli.Run("trace", file, "--format", "xml");

        Assert.Equal(2, exitCode);
        Assert.StartsWith("ncx(1): ERROR CLI001: ", _cli.Error, StringComparison.Ordinal);
    }

    // The help of trace names --format and the shared options (architecture 10, F28).
    [Fact]
    public void Trace_Help_NamesItsOptions()
    {
        int exitCode = _cli.Run("trace", "--help");

        Assert.Equal(0, exitCode);
        foreach (string option in new[] { "--format", "--machine", "--strict", "--skip-blocks", "--expand-cycles" })
        {
            Assert.Contains(option, _cli.Output, StringComparison.Ordinal);
        }
    }
}
