using System.Text;
using Ncx.Core.Model;
using Ncx.Core.Writing;

namespace Ncx.Cli.History;

/// <summary>
/// The text of ncx annotate: a copy of the program through the canonical writer with the previous values appended to
/// each block's trailing comment, LINE X=55.44 followed by the comment ; X 33.22 -> 55.44 in the canonical column, an
/// existing comment kept and the values after it after one space; the parser keeps them as the block's comment and the
/// virtual machine ignores them (virtual machine 6, D92).
/// </summary>
// TODO(question): virtual machine 6 shows the comment of one changed variable; it does not say how several variables
// of one block follow each other or how an unknown value reads, and 3.10 says that generated blocks appear in
// annotate with their origin without saying in what form, while 6 makes annotate a copy of the program that the
// parser reads, where a pseudo-word is an ERROR (D95). The variables follow each other in the order of trace,
// separated by a comma and a space; an unknown value reads ?, as in the payload of the events; a generated block
// stands as a comment line where the virtual machine executed it, "; generated by [coolant] THROUGH (requires):
// SPINDLE:TOOL=OFF ; SPINDLE:S1 CW -> OFF", and a block the expander rewrote in place as such a line, "rewritten by",
// before the block of the file, which then carries no values of its own, until that is answered.
internal static class AnnotatedText
{
    // An unknown value in a comment, as the payload of the events writes it (P1-05).
    private const string Unknown = "?";

    /// <summary>
    /// Writes the annotated copy of a program.
    /// </summary>
    /// <param name="program">The program the virtual machine ran, parsed and expanded.</param>
    /// <param name="annotations">The values of the first walk of every block.</param>
    /// <returns>The text, every line ended with the line ending of the program.</returns>
    public static string Write(NcxProgram program, AnnotationListener annotations)
    {
        // Every line ends with the line ending of the file, the last line too (language 3, Encoding).
        string lineEnding = program.LineEnding == LineEnding.CrLf ? "\r\n" : "\n";
        var text = new StringBuilder();

        // For every line of the file, a comment-only or blank line or a block, as the canonical writer interleaves
        // them: each trivia line before the first block of a greater line, written back as read (D92). A generated
        // block has the line of the block it was generated for (language 4.15), so it stands next to that block.
        int nextTrivia = 0;
        for (int index = 0; index < program.Blocks.Count; index++)
        {
            Block block = program.Blocks[index];
            while (nextTrivia < program.Trivia.Count && program.Trivia[nextTrivia].Line < block.Line)
            {
                text.Append(program.Trivia[nextTrivia].Text).Append(lineEnding);
                nextTrivia++;
            }

            IReadOnlyList<TraceRow> values = annotations.ValuesOf(index);
            if (block.Generated is GeneratedBlock generated)
            {
                text.Append(GeneratedLine(block, generated, values)).Append(lineEnding);
                if (generated.Placement == GeneratedPlacement.InPlace)
                {
                    text.Append(NcxWriter.WriteBlock(generated.Origin)).Append(lineEnding);
                }

                continue;
            }

            text.Append(NcxWriter.WriteBlock(WithValues(block, values))).Append(lineEnding);
        }

        // The trivia after the last block, the lines after FILE=END among them (D92).
        while (nextTrivia < program.Trivia.Count)
        {
            text.Append(program.Trivia[nextTrivia].Text).Append(lineEnding);
            nextTrivia++;
        }

        return text.ToString();
    }

    // The values follow the block's own comment after one space, or open the comment of a block without one; the
    // canonical writer puts it in its column (virtual machine 6, D92).
    private static Block WithValues(Block block, IReadOnlyList<TraceRow> values)
    {
        if (values.Count == 0)
        {
            return block;
        }

        string comment = block.Comment is null ? "; " + Values(values) : block.Comment + " " + Values(values);
        return block with { Comment = comment };
    }

    // A generated block as a comment line: its origin, its words in canonical order, then its values (virtual machine
    // 3.10, 6).
    private static string GeneratedLine(Block block, GeneratedBlock generated, IReadOnlyList<TraceRow> values)
    {
        string words = NcxWriter.WriteBlock(block with { Comment = null });
        string line = "; " + GeneratedOrigin.Describe(generated) + ": " + words;
        return values.Count == 0 ? line : line + " ; " + Values(values);
    }

    // X 33.22 -> 55.44 for every variable, in the order of trace.
    private static string Values(IReadOnlyList<TraceRow> values)
    {
        var texts = new List<string>();
        foreach (TraceRow value in values)
        {
            texts.Add(value.Variable + " " + Shown(value.OldValue) + " -> " + Shown(value.NewValue));
        }

        return string.Join(", ", texts);
    }

    private static string Shown(string value)
    {
        return value.Length == 0 ? Unknown : value;
    }
}
