using Ncx.Core.Model;

namespace Ncx.Cli.History;

/// <summary>
/// How trace and annotate name the origin of a generated block (virtual machine 3.10): the rule or the rewriter that
/// made it and why, "generated by [coolant] THROUGH (requires)" for a block before or after the block of the file,
/// "rewritten by [machine] limits (...)" for one that stands in its place (language 4.15).
/// </summary>
internal static class GeneratedOrigin
{
    /// <summary>
    /// The origin of a generated block as text.
    /// </summary>
    /// <param name="generated">The origin the block carries.</param>
    public static string Describe(GeneratedBlock generated)
    {
        string made = generated.Placement == GeneratedPlacement.InPlace ? "rewritten" : "generated";
        return $"{made} by {generated.Source} ({generated.Reason})";
    }
}
