using System.Globalization;
using System.Text;
using Ncx.Core.Model;

namespace Ncx.Cli.History;

/// <summary>
/// The table of ncx trace: the columns channel, block, variable, old, new, one row per changed state variable per
/// executed block (virtual machine 6), as plain text in aligned columns or as comma-separated values (8).
/// </summary>
// TODO(question): virtual machine 6 names the columns and 8 says "CSV or aligned columns", and neither says whether the
// table has a header row, which format is the default, how a CSV field is quoted, or how the block column shows the
// origin of a generated block that 3.10 asks for. The table starts with a header row of the column names, text is the
// default, a CSV field with a comma, a quote or a line break stands in quotes with its quotes doubled (RFC 4180), every
// line ends with LF, and a generated block is its line followed by its origin, "5 generated by [coolant] THROUGH
// (requires)", until that is answered.
internal static class TraceTable
{
    // Aligned columns stand two spaces apart.
    private const string ColumnGap = "  ";

    // The columns of virtual machine 6, in its order.
    private static readonly string[] s_columns = ["channel", "block", "variable", "old", "new"];

    /// <summary>
    /// Writes the table.
    /// </summary>
    /// <param name="rows">The rows of the run, in the order the virtual machine raised them.</param>
    /// <param name="format">Aligned text or CSV.</param>
    /// <returns>The table, the header row first, every line ended with LF.</returns>
    public static string Write(IReadOnlyList<TraceRow> rows, TraceFormat format)
    {
        var table = new List<string[]> { s_columns };
        foreach (TraceRow row in rows)
        {
            table.Add([
                row.Channel.ToString(CultureInfo.InvariantCulture),
                BlockText(row.Block),
                row.Variable,
                row.OldValue,
                row.NewValue,
            ]);
        }

        return format == TraceFormat.Csv ? Csv(table) : Aligned(table);
    }

    // The block by its line; a generated block, which has the line of the block it was generated for, with its origin
    // (virtual machine 3.10).
    private static string BlockText(Block block)
    {
        string line = block.Line.ToString(CultureInfo.InvariantCulture);
        return block.Generated is GeneratedBlock generated ? line + " " + GeneratedOrigin.Describe(generated) : line;
    }

    // Comma-separated values, one line per row.
    private static string Csv(List<string[]> table)
    {
        var text = new StringBuilder();
        foreach (string[] cells in table)
        {
            for (int column = 0; column < cells.Length; column++)
            {
                if (column > 0)
                {
                    text.Append(',');
                }

                text.Append(CsvField(cells[column]));
            }

            text.Append('\n');
        }

        return text.ToString();
    }

    // A field with a comma, a quote or a line break stands in quotes, and its quotes are doubled.
    private static string CsvField(string cell)
    {
        if (cell.IndexOfAny([',', '"', '\n', '\r']) < 0)
        {
            return cell;
        }

        return "\"" + cell.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";
    }

    // Every column as wide as its widest cell, the columns two spaces apart, no space at the end of a line.
    private static string Aligned(List<string[]> table)
    {
        var widths = new int[s_columns.Length];
        foreach (string[] cells in table)
        {
            for (int column = 0; column < cells.Length; column++)
            {
                widths[column] = Math.Max(widths[column], cells[column].Length);
            }
        }

        var text = new StringBuilder();
        foreach (string[] cells in table)
        {
            var line = new StringBuilder();
            for (int column = 0; column < cells.Length; column++)
            {
                if (column > 0)
                {
                    line.Append(ColumnGap);
                }

                line.Append(cells[column].PadRight(widths[column]));
            }

            text.Append(line.ToString().TrimEnd()).Append('\n');
        }

        return text.ToString();
    }
}
