using Ncx.Acceptance.Cli;
using Ncx.Cli;
using Ncx.Cli.Commands;
using Ncx.Cli.History;
using Ncx.Compilers;
using Ncx.Core.Machine;
using Ncx.Core.Model;
using Ncx.Core.Parsing;
using Ncx.Plugins;
using Ncx.Tests.Fixtures;

namespace Ncx.Acceptance.Plugins;

/// <summary>
/// The second "Done when" of P7-01: a plugin that throws in any of its four places is reported with its name as a PLG
/// ERROR and dropped for the run, which continues without it and never takes the command line down; a text a
/// rewriter inserts that does not parse is rejected with a PLG ERROR on its line (implementation 17, P7-01;
/// architecture 9; D95). The runs go through the commands with a working directory of their own (code-guidelines 8).
/// </summary>
public sealed class FailingPluginTests : IDisposable
{
    private readonly ProjectHarness _project = new(Fixture.RepositoryRoot());
    private readonly DirectoryInfo _folder = Directory.CreateTempSubdirectory("ncx-plugins-");

    // What the last command wrote to the standard output and to the standard error (D98).
    private string _output = "";
    private string _error = "";

    public FailingPluginTests()
    {
        _project.WriteInWorkingDirectory(Path.Combine("machines", "plugin-mill.toml"), PluginMachines.PlainMill);
    }

    public void Dispose()
    {
        _project.Dispose();
        _folder.Delete(recursive: true);
    }

    // Done when of P7-01: FaultyRules throws on the coolant block of line 5, is reported with its name and not asked
    // again, and the run goes on without it: ShopRules still inserts its blocks and trace writes their rows.
    [Fact]
    public void Rewrite_PluginThatThrows_IsReportedByNameAndTheRunContinuesWithoutIt()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.FaultyRules, TestPlugins.ShopRules);
        string file = _project.WriteInWorkingDirectory("part.ncx", CliHarness.OneProgram(
            "UNITS=MM", "SPINDLE:MAIN=CW RPM:MAIN=1500", "COOLANT:THROUGH=ON", "COOLANT:THROUGH=OFF"));

        int exitCode = Trace(file);

        Assert.Equal(1, exitCode);
        string failure = Assert.Single(LinesWith("PLG003"));
        Assert.StartsWith($"{file}(5): ERROR PLG003: plugin FaultyRules: Rewrite threw InvalidOperationException",
            failure, StringComparison.Ordinal);
        Assert.Contains("the shop table is missing", failure, StringComparison.Ordinal);
        Assert.Contains($"{file}(5): INFO PLG001: plugin ShopRules: inserted 3 blocks at line 5", _error,
            StringComparison.Ordinal);
        Assert.Contains("generated by ShopRules (the coolant clutch needs a standing spindle)", _output,
            StringComparison.Ordinal);
    }

    // Implementation 17, P7-01: a listener that throws on TOOL_BEGIN of line 4 is reported with the line of the event,
    // and the run goes on: the WARNING of the LINE of line 5, which cuts with the spindle off, is still reported.
    [Fact]
    public void On_ListenerThatThrows_IsReportedWithTheLineOfTheEventAndTheRunContinues()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.FaultyRules);
        string file = _project.WriteInWorkingDirectory("part.ncx",
            CliHarness.OneProgram("UNITS=MM", "TOOL=1", "LINE X=10 F=100"));

        int exitCode = _project.Check(file, "plugin-mill");

        Assert.Equal(1, exitCode);
        Assert.Contains($"{file}(4): ERROR PLG003: plugin FaultyRules: On threw InvalidOperationException",
            _project.Error, StringComparison.Ordinal);
        Assert.Contains($"{file}(5): WARNING VM500", _project.Error, StringComparison.Ordinal);
    }

    // Implementation 17, P7-01: a reader rule that throws on M457 of line 4 with a block begun is reported and
    // dropped; nothing it began stays behind, and the reader reads the block as it would without the plugin, an M
    // code no table names (architecture 7).
    [Fact]
    public void Read_ReaderRuleThatThrowsWithABlockBegun_IsReportedAndTheReaderReadsTheBlock()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.FaultyRules);
        string file = _project.WriteInWorkingDirectory("part.nc", "%\nO0004\nG90 G21 G17 G94\nM457\nM30\n%\n");

        int exitCode = Convert(file);

        Assert.Equal(1, exitCode);
        Assert.Contains($"{file}(4): ERROR PLG003: plugin FaultyRules: Read threw InvalidOperationException",
            _error, StringComparison.Ordinal);
        Assert.Contains("\nMFUNC=457", _output, StringComparison.Ordinal);
        Assert.DoesNotContain("COOLANT", _output, StringComparison.Ordinal);
    }

    // Implementation 17, P7-01: a block writer that edits the lines of the RAPID of line 4 and throws is reported and
    // dropped, and the lines stay as the compiler wrote them; the RAPID of line 5 is no longer handed to it.
    [Fact]
    public void Write_BlockWriterThatThrows_LeavesTheLinesAsTheCompilerWroteThem()
    {
        var diagnostics = new Diagnostics("part.ncx");
        PluginSet plugins = TestPlugins.Load(_folder.FullName, diagnostics, TestPlugins.FaultyRules);
        NcxProgram program = Parser.Parse(CliHarness.OneProgram("UNITS=MM", "RAPID X=0 Y=0 Z=5", "RAPID X=10"),
            "part.ncx", new ParserOptions());
        var options = new CompileOptions { Rewriters = plugins.Rewriters, BlockWriters = plugins.BlockWriters };

        CompileResult result = new EchoCompiler().Compile(program, PluginMachines.Load(PluginMachines.PlainMill),
            options);

        string text = Assert.Single(result.Files).Text;
        Assert.Contains("\nRAPID X=0 Y=0 Z=5\nRAPID X=10\n", text, StringComparison.Ordinal);
        Assert.DoesNotContain("EDITED", text, StringComparison.Ordinal);
        Diagnostic failure = Assert.Single(diagnostics.Items);
        Assert.Equal("PLG003", failure.Code);
        Assert.Equal(4, failure.Line);
        Assert.StartsWith("plugin FaultyRules: Write threw InvalidOperationException", failure.Message,
            StringComparison.Ordinal);
    }

    // Implementation 17, P7-01, and D205 as recommended: compile reports the block writer that throws, and writes no
    // file after the ERROR, because that file goes to a control.
    [Fact]
    public void Compile_BlockWriterThatThrows_IsReportedAndWritesNoFile()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.FaultyRules);
        string file = _project.WriteInWorkingDirectory("part.ncx",
            CliHarness.OneProgram("UNITS=MM", "RAPID X=0 Y=0 Z=5"));

        using var error = new StringWriter();
        int exitCode = CompileCommand.Run(Settings(file, "plugin-mill"), null, EchoCompilers(), error);
        _error = error.ToString();

        Assert.Equal(1, exitCode);
        Assert.Contains($"{file}(4): ERROR PLG003: plugin FaultyRules: Write threw", _error, StringComparison.Ordinal);
        Assert.False(Directory.Exists(Path.Combine(_project.WorkingDirectory, "out")));
    }

    // Implementation 17, P7-01, code-guidelines 10.3, D95: FOO=1, which FaultyRules inserts before each DWELL block,
    // does not parse; each answer is rejected with a PLG ERROR on the line of its block, the expander inserts nothing,
    // and the plugin is still asked about the blocks after it.
    [Fact]
    public void Rewrite_TextThatDoesNotParse_IsReportedWithTheLineAndInsertsNothing()
    {
        var diagnostics = new Diagnostics("part.ncx");
        PluginSet plugins = TestPlugins.Load(_folder.FullName, diagnostics, TestPlugins.FaultyRules);
        string program = CliHarness.OneProgram("UNITS=MM", "DWELL=2", "DWELL=3");

        NcxProgram expanded = PluginMachines.Expand(program, PluginMachines.PlainMill, plugins.Rewriters);

        Assert.Equal(program, PluginMachines.WriteWithGenerated(expanded));
        Assert.False(expanded.Diagnostics.HasErrors, expanded.Diagnostics.ToText());
        Assert.Equal(2, diagnostics.Items.Count);
        Assert.Equal([4, 5], [diagnostics.Items[0].Line, diagnostics.Items[1].Line]);
        Assert.All(diagnostics.Items, diagnostic => Assert.Equal("PLG004", diagnostic.Code));
        Assert.StartsWith("plugin FaultyRules: the block \"FOO=1\" ", diagnostics.Items[0].Message,
            StringComparison.Ordinal);
    }

    private string PluginsFolder => Path.Combine(_project.WorkingDirectory, PluginLoader.PluginsFolder);

    private RunSettings Settings(string file, string? machine)
    {
        return new RunSettings
        {
            File = file,
            MachineFile = machine,
            WorkingDirectory = _project.WorkingDirectory,
            ToolFolder = _project.ToolFolder,
        };
    }

    private int Trace(string file)
    {
        using var output = new StringWriter();
        using var error = new StringWriter();
        int exitCode = TraceCommand.Run(Settings(file, "plugin-mill"), TraceFormat.Text, output, error);
        _output = output.ToString();
        _error = error.ToString();
        return exitCode;
    }

    private int Convert(string file)
    {
        using var output = new StringWriter();
        using var error = new StringWriter();
        int exitCode = ConvertCommand.Run(Settings(file, "fanuc-mill-30i"), null, Program.Readers(), output, error);
        _output = output.ToString();
        _error = error.ToString();
        return exitCode;
    }

    private List<string> LinesWith(string code)
    {
        var lines = new List<string>();
        foreach (string line in _error.Split('\n'))
        {
            if (line.Contains(code, StringComparison.Ordinal))
            {
                lines.Add(line);
            }
        }

        return lines;
    }

    private static CompilerRegistry EchoCompilers()
    {
        var compilers = new CompilerRegistry();
        compilers.Register(Controller.Fanuc, () => new EchoCompiler());
        return compilers;
    }
}
