using Ncx.Acceptance.Cli;
using Ncx.Cli;
using Ncx.Cli.Commands;
using Ncx.Cli.History;
using Ncx.Compilers;
using Ncx.Core.Machine;
using Ncx.Plugins;
using Ncx.Tests.Fixtures;

namespace Ncx.Acceptance.Plugins;

/// <summary>
/// The composition root wires the plugins of the working directory into the four places (virtual machine 7;
/// architecture 9, 10; implementation 17, P7-01): the expander of check, trace and compile asks the rewriters, the
/// reader of convert asks the reader rules, the compiler hands BLOCK_WRITE to the block writers; the plugins come from
/// plugins/ and the [plugins] list of ncx.toml, with their [plugins.&lt;name&gt;] settings (D80). The runs go through
/// the commands with a working directory of their own (code-guidelines 8).
/// </summary>
public sealed class PluginWiringTests : IDisposable
{
    private static readonly string s_clutchProgram = CliHarness.OneProgram(
        "UNITS=MM",
        "SPINDLE:MAIN=CW RPM:MAIN=1500",
        "COOLANT:THROUGH=ON");

    private readonly ProjectHarness _project = new(Fixture.RepositoryRoot());

    // What the last command wrote to the standard output and to the standard error (D98).
    private string _output = "";
    private string _error = "";

    public PluginWiringTests()
    {
        _project.WriteInWorkingDirectory(Path.Combine("machines", "plugin-mill.toml"), PluginMachines.PlainMill);
    }

    public void Dispose()
    {
        _project.Dispose();
    }

    // Architecture 9, D98: check loads the DLLs of plugins/, the expander asks their rewriters, and the INFO line
    // names the plugin, the blocks it inserted and the line.
    [Fact]
    public void Check_PluginOfThePluginsFolder_InsertsItsBlocksAndSaysSo()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.ShopRules);
        string file = _project.WriteInWorkingDirectory("part.ncx", s_clutchProgram);

        int exitCode = _project.Check(file, "plugin-mill");

        Assert.True(exitCode == 0, _project.Error);
        Assert.Equal($"{file}(5): INFO PLG001: plugin ShopRules: inserted 3 blocks at line 5\n", _project.Error);
    }

    // Virtual machine 3.10, architecture 9: trace shows the blocks of a plugin with the plugin's name and its reason.
    [Fact]
    public void Trace_BlocksOfAPlugin_NameThePluginAsTheirOrigin()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.ShopRules);
        string file = _project.WriteInWorkingDirectory("part.ncx", s_clutchProgram);

        using var output = new StringWriter();
        using var error = new StringWriter();
        int exitCode = TraceCommand.Run(Settings(file, "plugin-mill"), TraceFormat.Text, output, error);

        Assert.True(exitCode == 0, error.ToString());
        Assert.Contains("generated by ShopRules (the coolant clutch needs a standing spindle)", output.ToString(),
            StringComparison.Ordinal);
    }

    // D80: the [plugins.ShopRules] section of ncx.toml arrives in the context of the plugin, whose DLL lies in
    // plugins/.
    [Fact]
    public void Check_SectionOfThePluginInNcxToml_ArrivesInItsContext()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.ShopRules);
        _project.WriteInWorkingDirectory("ncx.toml", "[plugins.ShopRules]\nbefore_tool = \"COOLANT=OFF\"\n");
        string file = _project.WriteInWorkingDirectory("part.ncx", CliHarness.OneProgram("UNITS=MM", "TOOL=1"));

        int exitCode = _project.Check(file, "plugin-mill");

        Assert.True(exitCode == 0, _project.Error);
        Assert.Equal($"{file}(4): INFO PLG001: plugin ShopRules: inserted 1 block at line 4\n", _project.Error);
    }

    // Machine-config 10, implementation 17 P7-01: the [plugins] list of ncx.toml names an assembly by its path from
    // the working directory, outside plugins/.
    [Fact]
    public void Check_AssemblyTheListOfNcxTomlNames_IsLoadedFromItsPath()
    {
        TestPlugins.CopyInto(Path.Combine(_project.WorkingDirectory, "lib"), TestPlugins.ShopRules);
        _project.WriteInWorkingDirectory("ncx.toml", "plugins = [\"lib/ShopRules.dll\"]\n");
        string file = _project.WriteInWorkingDirectory("part.ncx", s_clutchProgram);

        int exitCode = _project.Check(file, "plugin-mill");

        Assert.True(exitCode == 0, _project.Error);
        Assert.Equal($"{file}(5): INFO PLG001: plugin ShopRules: inserted 3 blocks at line 5\n", _project.Error);
    }

    // Implementation 17, P7-01: a DLL of plugins/ that is no assembly is reported by its name as a PLG ERROR, and the
    // run goes on with the other plugins.
    [Fact]
    public void Check_FileOfThePluginsFolderThatIsNoAssembly_IsReportedAndTheRunContinues()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.ShopRules);
        File.WriteAllText(Path.Combine(PluginsFolder, "Broken.dll"), "not an assembly");
        string file = _project.WriteInWorkingDirectory("part.ncx", s_clutchProgram);

        int exitCode = _project.Check(file, "plugin-mill");

        Assert.Equal(1, exitCode);
        Assert.StartsWith($"{Path.Combine("plugins", "Broken.dll")}(1): ERROR PLG002: plugin Broken: ",
            _project.Error, StringComparison.Ordinal);
        Assert.Contains($"{file}(5): INFO PLG001: plugin ShopRules: inserted 3 blocks at line 5", _project.Error,
            StringComparison.Ordinal);
    }

    // Architecture 9, D40, D66: convert offers the reader rules of the plugins the blocks the tables of the machine
    // leave undecided; ShopRules reads M456 as COOLANT=ON.
    [Fact]
    public void Convert_ReaderRuleOfAPlugin_ReadsACodeTheTablesLeaveUndecided()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.ShopRules);
        string file = _project.WriteInWorkingDirectory("part.nc", "%\nO0004\nG90 G21 G17 G94\nM456\nM30\n%\n");

        using var output = new StringWriter();
        using var error = new StringWriter();
        int exitCode = ConvertCommand.Run(Settings(file, "fanuc-mill-30i"), null, Program.Readers(), output, error);

        Assert.True(exitCode == 0, error.ToString());
        Assert.Contains("\nCOOLANT=ON\n", output.ToString(), StringComparison.Ordinal);
        Assert.DoesNotContain("MFUNC", output.ToString(), StringComparison.Ordinal);
    }

    // Virtual machine 7, architecture 8: compile hands BLOCK_WRITE with the lines of every block to the block writers
    // of the plugins before the lines reach the file; ShopRules puts Z on a line of its own.
    [Fact]
    public void Compile_BlockWriterOfAPlugin_EditsTheLinesBeforeTheyAreWritten()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.ShopRules);
        string file = _project.WriteInWorkingDirectory("part.ncx",
            CliHarness.OneProgram("UNITS=MM", "RAPID X=0 Y=0 Z=5"));

        int exitCode = Compile(file);

        Assert.True(exitCode == 0, _error);
        Assert.Contains("\nRAPID X=0 Y=0\nZ=5\n", CompiledText(), StringComparison.Ordinal);
    }

    // Architecture 5.5, 8, 9: compile expands with the rewriters of the plugins, and their blocks are compiled like
    // the rest: the stop, the coolant, and the restore as the words it applies again, which a Fanuc compiler writes as
    // M5, M51, M3 S1500 (virtual machine 3.10).
    [Fact]
    public void Compile_RewriterOfAPlugin_ItsBlocksAreCompiledLikeTheRest()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.ShopRules);
        string file = _project.WriteInWorkingDirectory("part.ncx", s_clutchProgram);

        int exitCode = Compile(file);

        Assert.True(exitCode == 0, _error);
        string text = CompiledText();
        string compiled = CliHarness.Lines(
            "SPINDLE:MAIN=CW RPM:MAIN=1500",
            "SPINDLE:MAIN=OFF",
            "COOLANT:THROUGH=ON",
            "SPINDLE:MAIN=CW RPM:MAIN=1500",
            "PROGRAM=END");
        Assert.True(text.Contains("\n" + compiled, StringComparison.Ordinal), text);
        Assert.Equal($"{file}(5): INFO PLG001: plugin ShopRules: inserted 3 blocks at line 5\n", _error);
    }

    // Virtual machine 7, architecture 9: the listeners of the plugins read every event of the STATIC run of compile as
    // of any other run; FaultyRules throws on TOOL_BEGIN of line 4 and is reported with its name, and compile writes no
    // file after the ERROR (implementation 17, P7-01; D205 as recommended).
    [Fact]
    public void Compile_ListenerOfAPluginThatThrows_IsReportedByNameAndNoFileIsWritten()
    {
        TestPlugins.CopyInto(PluginsFolder, TestPlugins.FaultyRules);
        string file = _project.WriteInWorkingDirectory("part.ncx", CliHarness.OneProgram("UNITS=MM", "TOOL=1"));

        int exitCode = Compile(file);

        Assert.Equal(1, exitCode);
        Assert.Contains($"{file}(4): ERROR PLG003: plugin FaultyRules: On threw InvalidOperationException", _error,
            StringComparison.Ordinal);
        Assert.False(Directory.Exists(Path.Combine(_project.WorkingDirectory, "out")), _error);
    }

    private string PluginsFolder => Path.Combine(_project.WorkingDirectory, PluginLoader.PluginsFolder);

    private RunSettings Settings(string file, string machine)
    {
        return new RunSettings
        {
            File = file,
            MachineFile = machine,
            WorkingDirectory = _project.WorkingDirectory,
            ToolFolder = _project.ToolFolder,
        };
    }

    private int Compile(string file)
    {
        var compilers = new CompilerRegistry();
        compilers.Register(Controller.Fanuc, () => new EchoCompiler());
        using var error = new StringWriter();
        int exitCode = CompileCommand.Run(Settings(file, "plugin-mill"), null, compilers, error);
        _error = error.ToString();
        return exitCode;
    }

    // The one file compile wrote into out/plugin-mill/.
    private string CompiledText()
    {
        string folder = Path.Combine(_project.WorkingDirectory, "out", "plugin-mill");
        _output = File.ReadAllText(Assert.Single(Directory.GetFiles(folder)));
        return _output;
    }
}
